name: hello1

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    hello2:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: hellow3
              run: echo "Hellow world"
              shell: bash
