name: Learning

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: echo
              run: echo "Hellow world"
              shell: bash
    javascript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/first
            - name: console
              run: echo "Hellow world"
              shell: bash
